/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnnualReportsRouteImport } from './routes/annual-reports'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExecutiveCommitteeRouteImport } from './routes/executive-committee'
import { Route as FinancialReportsRouteImport } from './routes/financial-reports'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as NewsEventsRouteImport } from './routes/news-events'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SmritiGramRouteImport } from './routes/smriti-gram'
import { Route as TheRoadAheadRouteImport } from './routes/the-road-ahead'
import { Route as NewsEventsSlugRouteImport } from './routes/news-events_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReportsRoute = AnnualReportsRouteImport.update({
  id: '/annual-reports',
  path: '/annual-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveCommitteeRoute = ExecutiveCommitteeRouteImport.update({
  id: '/executive-committee',
  path: '/executive-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialReportsRoute = FinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SmritiGramRoute = SmritiGramRouteImport.update({
  id: '/smriti-gram',
  path: '/smriti-gram',
  getParentRoute: () => rootRouteImport,
} as any)
const TheRoadAheadRoute = TheRoadAheadRouteImport.update({
  id: '/the-road-ahead',
  path: '/the-road-ahead',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsSlugRoute = NewsEventsSlugRouteImport.update({
  id: '/news-events_/$slug',
  path: '/news-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/contact': typeof ContactRoute
  '/executive-committee': typeof ExecutiveCommitteeRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/founders': typeof FoundersRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/news-events': typeof NewsEventsRoute
  '/services': typeof ServicesRoute
  '/smriti-gram': typeof SmritiGramRoute
  '/the-road-ahead': typeof TheRoadAheadRoute
  '/news-events/$slug': typeof NewsEventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/contact': typeof ContactRoute
  '/executive-committee': typeof ExecutiveCommitteeRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/founders': typeof FoundersRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/news-events': typeof NewsEventsRoute
  '/services': typeof ServicesRoute
  '/smriti-gram': typeof SmritiGramRoute
  '/the-road-ahead': typeof TheRoadAheadRoute
  '/news-events/$slug': typeof NewsEventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/annual-reports': typeof AnnualReportsRoute
  '/contact': typeof ContactRoute
  '/executive-committee': typeof ExecutiveCommitteeRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/founders': typeof FoundersRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/news-events': typeof NewsEventsRoute
  '/services': typeof ServicesRoute
  '/smriti-gram': typeof SmritiGramRoute
  '/the-road-ahead': typeof TheRoadAheadRoute
  '/news-events_/$slug': typeof NewsEventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/annual-reports'
    | '/contact'
    | '/executive-committee'
    | '/financial-reports'
    | '/founders'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/news-events'
    | '/services'
    | '/smriti-gram'
    | '/the-road-ahead'
    | '/news-events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/annual-reports'
    | '/contact'
    | '/executive-committee'
    | '/financial-reports'
    | '/founders'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/news-events'
    | '/services'
    | '/smriti-gram'
    | '/the-road-ahead'
    | '/news-events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/annual-reports'
    | '/contact'
    | '/executive-committee'
    | '/financial-reports'
    | '/founders'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/news-events'
    | '/services'
    | '/smriti-gram'
    | '/the-road-ahead'
    | '/news-events_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnualReportsRoute: typeof AnnualReportsRoute
  ContactRoute: typeof ContactRoute
  ExecutiveCommitteeRoute: typeof ExecutiveCommitteeRoute
  FinancialReportsRoute: typeof FinancialReportsRoute
  FoundersRoute: typeof FoundersRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  LeadershipRoute: typeof LeadershipRoute
  NewsEventsRoute: typeof NewsEventsRoute
  ServicesRoute: typeof ServicesRoute
  SmritiGramRoute: typeof SmritiGramRoute
  TheRoadAheadRoute: typeof TheRoadAheadRoute
  NewsEventsSlugRoute: typeof NewsEventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-reports': {
      id: '/annual-reports'
      path: '/annual-reports'
      fullPath: '/annual-reports'
      preLoaderRoute: typeof AnnualReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-committee': {
      id: '/executive-committee'
      path: '/executive-committee'
      fullPath: '/executive-committee'
      preLoaderRoute: typeof ExecutiveCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-reports': {
      id: '/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof FinancialReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events': {
      id: '/news-events'
      path: '/news-events'
      fullPath: '/news-events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smriti-gram': {
      id: '/smriti-gram'
      path: '/smriti-gram'
      fullPath: '/smriti-gram'
      preLoaderRoute: typeof SmritiGramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-road-ahead': {
      id: '/the-road-ahead'
      path: '/the-road-ahead'
      fullPath: '/the-road-ahead'
      preLoaderRoute: typeof TheRoadAheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events_/$slug': {
      id: '/news-events_/$slug'
      path: '/news-events/$slug'
      fullPath: '/news-events/$slug'
      preLoaderRoute: typeof NewsEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnualReportsRoute: AnnualReportsRoute,
  ContactRoute: ContactRoute,
  ExecutiveCommitteeRoute: ExecutiveCommitteeRoute,
  FinancialReportsRoute: FinancialReportsRoute,
  FoundersRoute: FoundersRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  LeadershipRoute: LeadershipRoute,
  NewsEventsRoute: NewsEventsRoute,
  ServicesRoute: ServicesRoute,
  SmritiGramRoute: SmritiGramRoute,
  TheRoadAheadRoute: TheRoadAheadRoute,
  NewsEventsSlugRoute: NewsEventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
